version: 2

updates:
  - package-ecosystem: github-actions
    directory: "/"
    commit-message:
      prefix: "(dependabot)"
    assignees:
      - "${{ secrets.GHA_REVIEWER }}"
    reviewers:
      - "${{ secrets.GHA_REVIEWER }}"
    schedule:
      interval: monthly

  - package-ecosystem: nuget
    directory: "/"
    commit-message:
      prefix: "(dependabot)"
    assignees:
      - "${{ secrets.NUGET_REVIEWER }}"
    reviewers:
      - "${{ secrets.NUGET_REVIEWER }}"
    schedule:
      interval: daily
    open-pull-requests-limit: 25
